### ISSUE TITLE
Please add the ability to get the process_group_instance id

### ISSUE THREAD

**Issue by nejoyer** [Dynatrace/OneAgent-SDK-for-dotnet#27]
**Is your feature request related to a problem? Please describe.**
We are using Azure App Services with the Dynatrace One Agent Site Extension. The problem is that this version of the OneAgent doesn't support autodiscovery of logs. So to get the logs out, we have written our own logger which sends the logs to the /ingest endpoint. We're using this SDK to get the TraceId and the SpanId to populate into the logs. But we can't find a way to programmatically get the process_group_instance id to properly link the logs to the service in Dynatrace.

**Describe the solution you'd like**
In the same way that the dynatraceSdk.TraceContextInfo exposes the TraceId and the SpanId, I'd love for it to expose the process group id.

**Describe alternatives you've considered**
We could manually look up the process group id in dynatrace and then add extra configuration to our logger, but we've got hundreds of services that occasionally change how they're detected in Dynatrace. It would be a lot of work and quite flakey to do this manually.

**Additional context**
Alternatively, I think Dynatrace already knows which process group was assigned to a given traceid, so maybe there is a Dynatrace logs ingest backend-fix where it could lookup the missing id and populate it?

**Comment by Oberon00** [comment]
Hi, this should be possible with the common OneAgent file-open interface documented at https://www.dynatrace.com/support/help/shortlink/enrich-metrics#oneagent-file-open-interface

Please tell me if that works for you.

**Comment by Oberon00** [comment]
There is a code snippet for .NET on how to read these files here: https://www.dynatrace.com/support/help/shortlink/opent-dotnet#send

This should cover what you need. If it does not work, you should open a support ticket, so that it can be looked into in more detail by the appropriate team. This is not really a SDK topic.

**Comment by nejoyer** [comment]
Thanks for your responses. I have filed a support ticket.
