### ISSUE TITLE
How to configure Dynatrace for custom request attribute tracing

### ISSUE THREAD

**Issue by kristianmandrup** [Dynatrace/OneAgent-SDK-for-dotnet#6]
Sorry to ask this question here but not sure how else to reach out in order to hopefully get a quick response. We have spent weeks on this already and feeling "my neck is on the line" if it takes much longer... You will also need better guide for when this feature lands in the SDK in any case

Trying to follow guide for [How do I capture request attributes based on .NET method arguments?](https://www.dynatrace.com/support/help/monitor/transactions-and-services/request-attributes/how-do-i-capture-request-attributes-based-on-dotnet-method-arguments/)

This post and the one for Web post start off with:

1. Go to Settings > Server-side monitoring > Request attributes.

However I can't seem to find that in my Dynatrace client. Is this controlled from the server side (where I don't have direct access)? or is it because the UI and interface/menus change between versions (I have Dynatrace 7 from 2017)

Would be great if you could add more screenshots to these step-by-step guides. Feeling lost.

Thank you so much!

**Comment by SonjaChevre** [comment]
Hi Kristian,

I see you have already asked this question on the Dynatrace community as well (https://answers.dynatrace.com/spaces/482/dynatrace-open-qa/questions/217283/how-do-i-configure-dynatrace-to-capture-request-at.html). 

This is the right place to place generic questions about Dynatrace in general - I will post an answer there. We try to keep the issues in the SDK GitHub really about the SDK usage.

Sonja

**Comment by kristianmandrup** [comment]
Sweet, thanks.
